// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// rBB_cpp
IntegerVector rBB_cpp(int k, NumericVector m, NumericVector p, double phi);
RcppExport SEXP _PROregTMB_rBB_cpp(SEXP kSEXP, SEXP mSEXP, SEXP pSEXP, SEXP phiSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type m(mSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type p(pSEXP);
    Rcpp::traits::input_parameter< double >::type phi(phiSEXP);
    rcpp_result_gen = Rcpp::wrap(rBB_cpp(k, m, p, phi));
    return rcpp_result_gen;
END_RCPP
}
// ldbb_cpp
NumericVector ldbb_cpp(NumericVector y, NumericVector m, NumericVector p, NumericVector phi);
RcppExport SEXP _PROregTMB_ldbb_cpp(SEXP ySEXP, SEXP mSEXP, SEXP pSEXP, SEXP phiSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< NumericVector >::type m(mSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type p(pSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type phi(phiSEXP);
    rcpp_result_gen = Rcpp::wrap(ldbb_cpp(y, m, p, phi));
    return rcpp_result_gen;
END_RCPP
}
// smooth_se_cpp
NumericVector smooth_se_cpp(NumericMatrix B, NumericMatrix V);
RcppExport SEXP _PROregTMB_smooth_se_cpp(SEXP BSEXP, SEXP VSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type B(BSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type V(VSEXP);
    rcpp_result_gen = Rcpp::wrap(smooth_se_cpp(B, V));
    return rcpp_result_gen;
END_RCPP
}
// dBB_cpp
NumericVector dBB_cpp(int m, double p, double phi);
RcppExport SEXP _PROregTMB_dBB_cpp(SEXP mSEXP, SEXP pSEXP, SEXP phiSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type m(mSEXP);
    Rcpp::traits::input_parameter< double >::type p(pSEXP);
    Rcpp::traits::input_parameter< double >::type phi(phiSEXP);
    rcpp_result_gen = Rcpp::wrap(dBB_cpp(m, p, phi));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_PROregTMB_rBB_cpp", (DL_FUNC) &_PROregTMB_rBB_cpp, 4},
    {"_PROregTMB_ldbb_cpp", (DL_FUNC) &_PROregTMB_ldbb_cpp, 4},
    {"_PROregTMB_smooth_se_cpp", (DL_FUNC) &_PROregTMB_smooth_se_cpp, 2},
    {"_PROregTMB_dBB_cpp", (DL_FUNC) &_PROregTMB_dBB_cpp, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_PROregTMB(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
