# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rBB_cpp <- function(k, m, p, phi) {
    .Call(`_PROregTMB_rBB_cpp`, k, m, p, phi)
}

ldbb_cpp <- function(y, m, p, phi) {
    .Call(`_PROregTMB_ldbb_cpp`, y, m, p, phi)
}

smooth_se_cpp <- function(B, V) {
    .Call(`_PROregTMB_smooth_se_cpp`, B, V)
}

dBB_cpp <- function(m, p, phi) {
    .Call(`_PROregTMB_dBB_cpp`, m, p, phi)
}

